### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by Vardanos** [ZiqiaoZhang/FraGAT#1]
Hello, I am trying to use your code, but I think NaiveGCN file is missing

![image](https://user-images.githubusercontent.com/31112423/114831864-e712c680-9dde-11eb-9630-b8ec4b01702a.png)

Am I missing something?

**Comment by ZiqiaoZhang** [comment]
I'm sorry for the missing of the NaiveGCN.py.
However,  this file is now deprecated in our code, together with the class MolPredGraph and MolPredFP. We only use the class MolPredFragFPv8 with AttentiveFP module, rather than the NaiveGCN.
You can try to delete this line, and the code will work.

A concise and verified version will be uploaded in a few days.

**Comment by Vardanos** [comment]
Thank you very much.

**Comment by thegodone** [comment]
Can you add a jupyter notebook example on Freesolv or ESOL please ?
